language: cpp
dist: trusty
branches:
  except:
    - latest-master

before_install:
  - export BUILD_PSP=YES
  - export BUILD_ANDROID=YES
  - export BUILD_Qt=YES
  - export BUILD_MAC=NO
# Only building on Mac when not handling pull request
# - if [ "$TRAVIS_PULL_REQUEST" ==  "false" ]; then
#     export BUILD_MAC=YES;
#   fi
  - sudo apt-get update -qq
# Building for PSP here
  - if [ "$BUILD_PSP" == "YES" ]; then
      export PSPDEV="$TRAVIS_BUILD_DIR/opt/pspsdk" &&
      export PSPSDK="$PSPDEV/psp/sdk" &&
      export PATH="$PATH:$PSPDEV/bin:$PSPSDK/bin" &&
      wget -O sdk.lzma http://downloads.sourceforge.net/project/minpspw/SDK%20%2B%20devpak/pspsdk%200.11.2/minpspw_0.11.2-amd64.tar.lzma;
    fi
# Building for Qt here
  - if [ "$BUILD_Qt" == "YES" ]; then
      sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe" &&
      sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main" &&
      sudo apt-get -qq update &&
      sudo apt-get -qq install qt5-qmake qtbase5-dev qtdeclarative5-dev qttools5-dev qtmultimedia5-dev pulseaudio libpulse-dev &&
      export QMAKE="qmake -qt=qt5";
    fi
# Building for Android here
  - if [ "$BUILD_ANDROID" == "YES" ]; then
      export ANDROID="android-sdk-linux/tools/android" &&
      if [ `uname -m` = x86_64 ]; then 
        sudo dpkg --add-architecture i386 && sudo apt-get update &&
        sudo apt-get install -qq --force-yes libgd2-xpm-dev libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1 jq ant; fi &&
      wget http://dl.google.com/android/ndk/android-ndk-r9-linux-x86_64.tar.bz2 -nv &&
      wget http://dl.google.com/android/android-sdk_r24.3.4-linux.tgz -nv;
    fi
    
install:
- if [ "$BUILD_PSP" == "YES" ]; then
    tar -x --xz -f sdk.lzma;
  fi
- if [ "$BUILD_ANDROID" == "YES" ]; then
    tar --absolute-names -jxf android-ndk-r9-linux-x86_64.tar.bz2 &&
    tar -zxf android-sdk_r24.3.4-linux.tgz &&
    $ANDROID list sdk --extended -a &&
    echo yes | $ANDROID update sdk -a -t tools,platform-tools,build-tools-23.0.1,android-23 --no-ui --force --no-https;
  fi
- sudo python -m easy_install --upgrade pyOpenSSL
- sudo pip install pyjavaproperties
- sudo pip install github3.py
- sudo pip install cpp-coveralls

env:
  global:
  #- secure: "EBzr1+qjQsOhn0s+tcFmXR1jP9B0xiOSXuXbRXWZ1OEHNvp8+A5/pS84LYVFlaZqmxr5dApxvPtwhgLIUbQ3EPXm8LpC3KgSD4dS+9/QMbxhe5TK4oczgFRGcDTMJQZsCzhOh7hp3tbcbJg5Gp+VT7aFjFQSHDGwhzSJXsXwh/8="
  #- secure: "X5dTQfofqAutnXxmu11Ep2MQ5QYnMN8m0AITRtwymhEF2UclcOudI1+skPtuhAGbWQnSO+lhunV3cvMfw2/Ml3k/VDz6VdFSKFrzAu7ja1VLJfcxr7chi0s8q30pVBb66tGydjIBac3B+RQyqgmZQW1frbRrhC/kPFQ6wPWOJdQ="
  #- secure: "T97NUPnxCpVZ/c5HH0zfo0FO3DPSRMSmze58ubW5EUTZOjAMtEt+OFdsrNZvUTCugUj2M1agtonZbAbczpaAL+lgZcHDgXgWMkfO0pMnsWX1yyCNqMuE/iTMpJr/xsLQeyWlftWjJLsseQU45abZsd1XVmda/G+ZhrDLF1y55SA="
  - secure: "m/c2RUcX8xr0qYXPqwV52+U2qRm28uvsPeAuKpZd2R1meeqbTLqdQRwk5zM4PWX1dyJAuk0norF4/TwFawVGjjv8umaebXnol8xJCPzunnHuGHdeMsaC9SdD5zZ1GWW4MPeCwK9zk99TWk7TDk/2UgYtulbn/7AfkwpIKXh9NJ/rbe2RNZ+vzNUcufMCyR4Uwytkoi/rgPxvVT1rT9H4x3LdUWyU4jL7q6mf5iqWqUSi3mrjGbowi1Zw823LS/lAGlaVtODK8s8D51RQczzG4Xh19S9pJt6oUQXTx1YYUFDQPPUSa2pZDqMAYgPwYUXkIIe+HLSNQLKW+/n/WoOkDcKa5vz3ChXeK/GFeKI83doE4szxKCwYWcC2aSXWUhRQdW63yTCe9kGs/fG5EaKBdLGp6mT5oagqUj7JBe/N5PaihaA6nKjY5a7VWeXsoGVBUIrElyciOR5ZUf6upoOz2mdklXZjAvre4StVbGMY7x7HJXTlqg/rjUsmOKm+d1DfOdHwX5areT5yxnPLmG6MLpJqQY+Qzhw7Aw6gkBWjsNofptMerly5eh02Qwv2vmXxsVT82dIBrDU+tyuiqBjFicSHIoxUg/wG5SMxXSKfxAIwsDx6V2VwsCgPKSSMpbqzsdzpknYBq3FiGYr1Skgy5ZapgZfz8/TWWNf/c+928Ss="
  - secure: "A5PZJ5D1gBf7/r0DOV+lkuFKMfa248VskmkzrYF57Qhpei77KFU4hdFEFPvpXWBMv7BzJcbaYfiWEd9fSZhu+iBh95eV8ehwhDDB/37y53YkeDkxwYu6TyVh3T0+ziUHpfR38xb3v8gRIBAfuQAIsPVYzBz5x8vKkK1gR45GRpXzZeGgtuUVANmde/0JAbQShSUXN5bHnk9anl1IMFeryExY6dcxKV12vmBvxjMYZ1QkfimZDVE9yUcDpFpO84xxjvk3BRjV42GADcoeu67J4fS3IhJMY7nWbnw76gH3wrEVkIWE1K2PXJBOiiTAlQknpuS1YBPFwPixxJIXqcHImsYzgzVN/vpCAggd+z55vtJ3r2s90TV9khJb7C8ENrxK+UC6rFZ4YqwQOJxwaSun7qNgA3nYKpMVdyJdA/BLmVDvfglKylEE6MarXLDTzbQdOl6eWIzlSI8sxBpzqLkpXubz/Yk8mecDJSMvDfNEBTFByEN4JtvaBY4lXhoHVsfOhG1dkluTwlObUwQjaNrMUNTSElz5RLp/eXd6NT1nA7R5eS5UZW8m1mLkpYBlAls+vlKMN5Ct6i0XgnACPltW8c4OJZ8ivF9MLsYjsRTjjh3eERcifloRTRs5BrAUvyd5XtqjrwqdNF8EY2CJiRDHm9g4splrxCHOYkVcWtIi1MA="
  - secure: "kg6Gbs5ijUKnhcE+XnpOXTIRZWyYYVmQaNPIMUcNAc09rOMoaS4sftbxEeqn5UoJR8WBrOUK/c5TIDYTTDjKh+/pHILfZzzfA1+iJ23R9ikmh8gUHjAdbvqkh0qCpjY78JqnpUq8AOCOM6YQD8PQLMiZEHBMzKs2LeBuCT9VA98mmF7PedVPr5J0x2s0z/QGcVNJRBWBnkZQFMtnDrgoPJaa+HuMquWtbkUpLSikOzldhPUuru38wKAICvgoUln1qzDgdoYtvwIDdyjSkcgQgUt3CSZ3Ken/FrVo0PlJBIF8JncyxgqB1khg/kjo4WtyNVVfq9h47I1ZFEO9qlrmWnwMxDoJPEMN9CZcpVOc3TEjYi5DLb3I9fDhxs07Fp3zTD5rwCLPRgio1f3eURdg6rdtYxsfiCh3ECNOm0qnsMuxr8tGYMLNEVfLErCOOyTOBkQcusLaOgVzrsZtHnB7Tc4Sjfw35Aaoqo7AW/bA41pdqQeqF2WcCk+1FW0WDiViH6QclsaAPPtfkIU03hWYUpBKO+NZZl6zBOlLAzsjJkGzCtuUoGq534fDdIOH8PiH3P36BnGTgLiDCY1ZbOpivCuajNwZMVsObY8UKIKQ5b1pz7b296A5Xy/LkK8kju/Ftpx5iYJUxXojkpw6k83CaC/QaGNNrxN4u4YeVH694ec="
 
script: "tools/travis-script.sh"

after_success:
- coveralls -b . -e JGE/src -e JGE/include -i projects/mtg/include -i projects/mtg/src --gcov-options '\-lp'
- python tools/upload-binaries.py -t $GH_TOKEN -s $TRAVIS_COMMIT -l core.zip -r Wagic-core.zip -b $TRAVIS_BRANCH
- python tools/upload-binaries.py -t $GH_TOKEN -s $TRAVIS_COMMIT -l projects/mtg/Android/bin/Wagic-debug.apk -r Wagic-android.apk -b $TRAVIS_BRANCH
- python tools/upload-binaries.py -t $GH_TOKEN -s $TRAVIS_COMMIT -l projects/mtg/psprelease.zip -r Wagic-psp.zip -b $TRAVIS_BRANCH
- python tools/upload-binaries.py -t $GH_TOKEN -s $TRAVIS_COMMIT -l qt-gui-build/linuxqtrelease.zip -r Wagic-linux-QT.zip -b $TRAVIS_BRANCH
