language: cpp
dist: trusty
branches:
  except:
    - latest-master

before_install:
  - export BUILD_PSP=YES
  - export BUILD_ANDROID=YES
  - export BUILD_Qt=YES
  - export BUILD_MAC=NO
# Only building on Mac when not handling pull request
# - if [ "$TRAVIS_PULL_REQUEST" ==  "false" ]; then
#     export BUILD_MAC=YES;
#   fi
  - sudo apt-get update -qq
# Building for PSP here
  - if [ "$BUILD_PSP" == "YES" ]; then
      export PSPDEV="$TRAVIS_BUILD_DIR/opt/pspsdk" &&
      export PSPSDK="$PSPDEV/psp/sdk" &&
      export PATH="$PATH:$PSPDEV/bin:$PSPSDK/bin" &&
      wget -O sdk.lzma http://downloads.sourceforge.net/project/minpspw/SDK%20%2B%20devpak/pspsdk%200.11.2/minpspw_0.11.2-amd64.tar.lzma;
    fi
# Building for Qt here
  - if [ "$BUILD_Qt" == "YES" ]; then
      sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe" &&
      sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main" &&
      sudo apt-get -qq update &&
      sudo apt-get -qq install qt5-qmake qtbase5-dev qtdeclarative5-dev qttools5-dev qtmultimedia5-dev pulseaudio libpulse-dev &&
      export QMAKE="qmake -qt=qt5";
    fi
# Building for Android here
  - if [ "$BUILD_ANDROID" == "YES" ]; then
      export ANDROID="android-sdk-linux/tools/android" &&
      if [ `uname -m` = x86_64 ]; then 
        sudo dpkg --add-architecture i386 && sudo apt-get update &&
        sudo apt-get install -qq --force-yes libgd2-xpm-dev libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1 jq ant; fi &&
      wget http://dl.google.com/android/ndk/android-ndk-r9-linux-x86_64.tar.bz2 -nv &&
      wget http://dl.google.com/android/android-sdk_r24.3.4-linux.tgz -nv;
    fi
    
install:
- if [ "$BUILD_PSP" == "YES" ]; then
    tar -x --xz -f sdk.lzma;
  fi
- if [ "$BUILD_ANDROID" == "YES" ]; then
    tar --absolute-names -jxf android-ndk-r9-linux-x86_64.tar.bz2 &&
    tar -zxf android-sdk_r24.3.4-linux.tgz &&
    $ANDROID list sdk --extended -a &&
    echo yes | $ANDROID update sdk -a -t tools,platform-tools,build-tools-23.0.1,android-23 --no-ui --force --no-https;
  fi
- sudo python -m easy_install --upgrade pyOpenSSL
- sudo pip install pyjavaproperties
- sudo pip install github3.py
- sudo pip install cpp-coveralls

env:
  global:
  #- secure: "EBzr1+qjQsOhn0s+tcFmXR1jP9B0xiOSXuXbRXWZ1OEHNvp8+A5/pS84LYVFlaZqmxr5dApxvPtwhgLIUbQ3EPXm8LpC3KgSD4dS+9/QMbxhe5TK4oczgFRGcDTMJQZsCzhOh7hp3tbcbJg5Gp+VT7aFjFQSHDGwhzSJXsXwh/8="
  #- secure: "X5dTQfofqAutnXxmu11Ep2MQ5QYnMN8m0AITRtwymhEF2UclcOudI1+skPtuhAGbWQnSO+lhunV3cvMfw2/Ml3k/VDz6VdFSKFrzAu7ja1VLJfcxr7chi0s8q30pVBb66tGydjIBac3B+RQyqgmZQW1frbRrhC/kPFQ6wPWOJdQ="
  #- secure: "T97NUPnxCpVZ/c5HH0zfo0FO3DPSRMSmze58ubW5EUTZOjAMtEt+OFdsrNZvUTCugUj2M1agtonZbAbczpaAL+lgZcHDgXgWMkfO0pMnsWX1yyCNqMuE/iTMpJr/xsLQeyWlftWjJLsseQU45abZsd1XVmda/G+ZhrDLF1y55SA="
  - secure: "kg4bVoinUc+HKCy7rcmUabh3Hf15inN1kP0p6pzzv0H6Xmbi59J30QT7Fxiccca5yjcBSFglhOqIbGCdCHAuQaAp4lo3sV91llmQxBx0jrju6+vNp2r9DUY/idT9/Nxj33eLI83Qp0E8BwygEdXDGXF2wXFdrJOkk9Qsvj7vrT1Du/12ShRIjlFORDmPHhH8tYHK0qXT9LeTUnF0QV6G6em8YfyVM/q4VRfsE8R9ttX54dBw57moILWGAAfxkyYxlEU89Hk1IVfn5pf5bwq8NPcUiuKSLoV2wS8xzlbNlhBL/hSeF7c9cIGoNG8Jy9nuJnwk6oN/pPHg3KCgT2nTo+ZwCBH2LBe2WfKEiM8sqphxfnnr25Ww34/eEAZw9WVLoFucfr1mqwA/U7McbXN1Wxs9oKiSHTT0b+RxudFHc37WdoZZajzEfC9OGcN4fj1/W3K4VrsPVdCU9i1IIYLR6lwkS9LM6smJQ1vbiTpCX8lDublcOR6F/7uGyESTnfN23qP3scSwGJ2oLzaIYBOzHoNCI5RgRH4iSKoHYaOjO0kdPMk6AsHgWxbdGhBVt3Rn1lgFsDatOREW+qUzNTpdMxN+zWRb6jC6R6YrcEhvGY4NQB1pMyBbxofMiG+0ns7p4NdOm9hlsduNcTK+xGyzEA7onsRNYqz9Ll1xiQVCQGE="
  - secure: "SdfoimDq0J3PgErsW/9q/gna8UGtBOWkQucxBPzkclN8Rw/4jiPfw5q+KH47BT/7B4bOvWhcl1cRcKy8yosGv2TZ6MqEwV75gqp2hWhKLiPJbhIPeVaO9avcNLLOrIn8+2BkGdgB92B+jkhzfcoWEnUepkTggPWXoAs5HkUV9pY6fz926M1lL8AcjHoZtfW4Fpm051W2JIw/4QG5E1CSMZ15EXnPTaTxGNkrj1FMAw0cfvuDCYnG8vxkEQ631V/uYMCQtcAukbidAfIUn2q1j0koi78DWIUC5+Fk3YlVjoGMsxncZqOLDruJJ3h0kjtjDUVJnq05Yu8cErsth1HV+Zl0JIVyZsW8u8fbtyh48HRscxSpp0eE7btAxfbeonMVOWG15d8ZdWquWy4YgQwxVd3ZUnvr+sik3JxF+/GZGk8pYQOK3JraYjEyWUMzrl40R9By27vjD1dSFHvoHLWutOcQln+Ff7rImdhHjpLAzQJWtYugeX3xXYp+et350+00HBT9lTYOLxsFHfwgjn3vyU7fqDzSIcmKzpqMP6g9fhI1OuYFBQcCFqcsEmJtU6W5CxbbswGZgBxS2Aol0sJsybTsY3Vvbq7R+Ii4EIc1BAUzuzOrDKwaDqm+Ab10QrFK3QA6QqmL9uyOh+rJvQnXY4Z4NBbmYq+9t+yZoFGLgfk="
  - secure: "hPffNWdaV+D+MLTsnJUryB1ID656JuTsJjvvrBHNJ4rP5nbTbksAEeLaugFNQISdLpobX62zhswmjPdNMjqSKNUg0R8/8U2pFAPYtzkeW0fIgqkxzxg8z1bt/MIZGTRph0lw83qjwFKsWGi9OQDnS4j5FghB0Fy38TO/VosTBqOLzlTt42oPlQvgxGD7VZwbKBhm51XeN0WBu82dPOjEybG7ehdYMA4Q+yZs7TP7ZZz4oEYGi1xdAplRNwjYiv7aZYlUggwgsO8ZyopXXVMAYl1BRjrBxk4V05H2Fhp1FAHFGMalaWW4Aw/e0Eqx6iqKSQm4iBUkMURp1A82MBT2c/QUaJm4sZK0NysTNEoLIvj480NshnpQWP69TUqiy9dbPf91L1ehxmE8+GIXwEyQtbbnLl6FRb075iscfpgRl5YjxXSGSyQWAbEXPMuwMRp062hCbPTCd1ILcT9/OODhAH56I4i1TJSQQEtx4l38GIGwugk7B2Hcjatq7+UR01T+fBGpiJVwzDU9P96etJpXIN0ZscXIIEzJAivVeEFPC6sWUD6jKUUaB4df4omE2eTa9LdFSsYYOqDRzZ5R1M0E6Qlwu4tkpDLvSZjE8W4EpQRTab9TcbtoYy5HlciL0CRmt9snLJsbY1VgZmTUanl9tYtZmHZoheNew6NdbywRYQE="
 
script: "tools/travis-script.sh"

after_success:
- coveralls -b . -e JGE/src -e JGE/include -i projects/mtg/include -i projects/mtg/src --gcov-options '\-lp'
- python tools/upload-binaries.py -t $GH_TOKEN -s $TRAVIS_COMMIT -l core.zip -r Wagic-core.zip -b $TRAVIS_BRANCH
- python tools/upload-binaries.py -t $GH_TOKEN -s $TRAVIS_COMMIT -l projects/mtg/Android/bin/Wagic-debug.apk -r Wagic-android.apk -b $TRAVIS_BRANCH
- python tools/upload-binaries.py -t $GH_TOKEN -s $TRAVIS_COMMIT -l projects/mtg/psprelease.zip -r Wagic-psp.zip -b $TRAVIS_BRANCH
- python tools/upload-binaries.py -t $GH_TOKEN -s $TRAVIS_COMMIT -l qt-gui-build/linuxqtrelease.zip -r Wagic-linux-QT.zip -b $TRAVIS_BRANCH
